<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <Import Project="Build/ModuleAssemblyManifest.targets" />
</Project>
